"""Regenerate ``fixtures/stem/porter_reference_vectors.tsv`` from an independent Porter.

The expected stems are **not** produced by ``wordextract.stem``: they come from NLTK's
``PorterStemmer(mode="ORIGINAL_ALGORITHM")``, a separate implementation of M. F. Porter,
*An algorithm for suffix stripping* (Program 14(3), 1980) in its faithful-to-the-paper mode.
A stemmer tested only against a table it produced proves that it agrees with itself; this
is the external check the build spec asks for (Turn 6b: "tested against external published
vectors"). Words come from English text already on the machine (Python's documentation and
standard library) plus a contract vocabulary, sampled deterministically.

Needs ``pip install nltk`` (not a project dependency: it is a dev-time generator only).

Run:  python tools/make_stem_vectors.py
"""
from pathlib import Path
import glob
import re
import sys

try:
    from nltk import __version__ as NLTK_VERSION
    from nltk.stem.porter import PorterStemmer
except ImportError:  # pragma: no cover - a dev-time tool
    sys.exit("pip install nltk to regenerate the vectors")

OUT = Path(__file__).resolve().parents[1] / "fixtures" / "stem" / "porter_reference_vectors.tsv"

VOCABULARY = (
    "universe universes university universities universal universally customer customers vendor "
    "vendors liability liabilities liable termination terminations terminated terminating renew "
    "renewal renewals renewed renewing waiver waivers exclusion exclusions excluded excluding "
    "included including inclusion limits limited limitation covered covers covering endorsement "
    "endorsements invoice invoices aggregate aggregated cancellation cancelled canceling contract "
    "contracts contractor contractors contractual indemnity indemnify indemnification indemnified "
    "reliability negligence negligent negligently agreement agreements settlement payment "
    "payments requirement requirements statement statements amendment amendments replacement "
    "adjustment adjustments enforcement document documents element elements movement placement "
    "argument instrument"
).split()


def main() -> None:
    import sysconfig

    lib = Path(sysconfig.get_paths()["stdlib"])
    words: set[str] = set()
    for path in glob.glob(str(lib / "**" / "*.py"), recursive=True)[:1500] + glob.glob(
        str(lib / "**" / "*.txt"), recursive=True
    ):
        try:
            text = Path(path).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        words.update(w.lower() for w in re.findall(r"[A-Za-z]{3,20}", text))
    ordered = sorted(words)
    sample = set(ordered[::25]) | set(VOCABULARY)
    # every word the ment-family defect touched is pinned, whatever the sample caught
    sample |= {w for w in ordered if w.endswith(("ment", "ments", "menting", "mented"))}
    stemmer = PorterStemmer(mode="ORIGINAL_ALGORITHM")
    lines = [
        "# Porter stemmer reference vectors: <word>\t<stem>",
        f"# Generated by tools/make_stem_vectors.py from nltk {NLTK_VERSION}, "
        "PorterStemmer(mode='ORIGINAL_ALGORITHM') -- an implementation independent of",
        "# wordextract.stem. Algorithm: M. F. Porter, 'An algorithm for suffix stripping',",
        "# Program 14(3):130-137, 1980. Do not edit by hand; regenerate with the tool.",
    ]
    lines += [f"{w}\t{stemmer.stem(w)}" for w in sorted(sample)]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(sample)} vectors to {OUT}")


if __name__ == "__main__":
    main()
